create table if not exists public.boards (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  description text not null default '',
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  board_id bigint not null references public.boards(id) on delete cascade,
  title text not null,
  description text not null default '',
  priority text not null check (priority in ('Alta', 'Media', 'Baixa')),
  created_date date not null,
  due_date date not null,
  assignee text not null,
  tags text[] not null default '{}',
  column_id text not null check (column_id in ('backlog', 'doing', 'review', 'done')),
  effort text not null default '45m',
  attachment_name text,
  attachment_url text,
  image_url text,
  checklist jsonb not null default '[]'::jsonb,
  comments jsonb not null default '[]'::jsonb,
  position integer not null default 0,
  inserted_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create or replace function public.handle_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists boards_set_updated_at on public.boards;
create trigger boards_set_updated_at
before update on public.boards
for each row
execute function public.handle_updated_at();

drop trigger if exists tasks_set_updated_at on public.tasks;
create trigger tasks_set_updated_at
before update on public.tasks
for each row
execute function public.handle_updated_at();

alter table public.boards enable row level security;
alter table public.tasks enable row level security;

drop policy if exists boards_select_own on public.boards;
create policy boards_select_own on public.boards
for select using (auth.uid() = user_id);

drop policy if exists boards_insert_own on public.boards;
create policy boards_insert_own on public.boards
for insert with check (auth.uid() = user_id);

drop policy if exists boards_update_own on public.boards;
create policy boards_update_own on public.boards
for update using (auth.uid() = user_id);

drop policy if exists boards_delete_own on public.boards;
create policy boards_delete_own on public.boards
for delete using (auth.uid() = user_id);

drop policy if exists tasks_select_own on public.tasks;
create policy tasks_select_own on public.tasks
for select using (
  exists (select 1 from public.boards b where b.id = board_id and b.user_id = auth.uid())
);

drop policy if exists tasks_insert_own on public.tasks;
create policy tasks_insert_own on public.tasks
for insert with check (
  exists (select 1 from public.boards b where b.id = board_id and b.user_id = auth.uid())
);

drop policy if exists tasks_update_own on public.tasks;
create policy tasks_update_own on public.tasks
for update using (
  exists (select 1 from public.boards b where b.id = board_id and b.user_id = auth.uid())
);

drop policy if exists tasks_delete_own on public.tasks;
create policy tasks_delete_own on public.tasks
for delete using (
  exists (select 1 from public.boards b where b.id = board_id and b.user_id = auth.uid())
);
